ci:
  autoupdate_schedule: quarterly
repos:
  # Fixes end of line, trailing whitespace, checks yaml and large files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=6000]
  # Ruff linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      # Ruff fix
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
        name: ruff (fix)
      - id: ruff-format
        # Ruff formatter
        types_or: [python, pyi]
        name: ruff (format)
  # yamlfmt for yaml formatting
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        name: YAML (format)
        types: [yaml]
  # nbstripout to remove output from Jupyter notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout
  # codespell for spell checking
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        files: ^.*\.(py|c|h|md|rst|yml)$
        args: ["--ignore-words", ".codespellignore"]
  # pyright for type checking
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types_or: [python, pyi]
